export const PROJECTS = [
  {
    slug: "poof",
    name: "POOF",
    desc: "Drop a file, get a link — no sign-up, no friction. Supports multi-file uploads as a single zip link, resumable downloads via HTTP range requests, SHA-256 deduplication, malware scanning via VirusTotal, and automatic 24-hour expiry. Files go directly from your browser to Cloudflare R2 — the server never touches your bytes.",
    tags: ["Next.js", "Vercel", "Cloudflare R2", "D1", "Upstash"],
    status: "live",
    live: "https://poof-file-sharing.vercel.app/",
    gh: "https://github.com/shyamsinghnegi/POOF-File-sharing",
    slot: "a",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js + Vercel" },
      { layer: "Storage", tech: "Cloudflare R2" },
      { layer: "Metadata / DB", tech: "Cloudflare D1" },
      { layer: "Rate limiting", tech: "Upstash Redis" },
    ],
    features: [
      { title: "Direct-to-storage uploads", body: "Files stream straight from the browser to Cloudflare R2 via signed URLs — the server never buffers or touches file bytes." },
      { title: "Multi-file zip links", body: "Multiple files in one drop are bundled and shared as a single link, generated on the fly." },
      { title: "Resumable downloads", body: "HTTP range requests let large downloads resume after a dropped connection instead of restarting." },
      { title: "Automatic expiry", body: "Every upload is deleted after 24 hours by default, so nothing lingers." },
    ],
    getStarted: [
      "Open the live site and drag a file (or a folder) onto the drop zone.",
      "Wait for the SHA-256 dedupe + VirusTotal scan to clear.",
      "Copy the generated link and share it — it self-destructs in 24 hours.",
    ],
  },
  {
    slug: "floatchat",
    name: "FloatChat",
    desc: "Query and visualise ARGO ocean data in plain language — RAG pipeline over NetCDF datasets.",
    tags: ["Python", "LLM", "RAG", "TypeScript"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/FloatChat",
    slot: "b",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Data ingestion", tech: "Python, NetCDF (ARGO floats)" },
      { layer: "Retrieval", tech: "RAG pipeline over parsed ocean datasets" },
      { layer: "Frontend", tech: "TypeScript" },
    ],
    features: [
      { title: "Plain-language queries", body: "Ask questions about ocean temperature, salinity, and float trajectories without writing NetCDF queries by hand." },
      { title: "RAG over real datasets", body: "Retrieval-augmented generation grounds answers in the actual ARGO float data rather than hallucinating numbers." },
    ],
    getStarted: [
      "Clone the repo and follow the setup instructions in the README.",
      "Point it at a local or remote ARGO NetCDF dataset.",
      "Ask a question in plain language and get a grounded answer plus a chart.",
    ],
  },
  {
    slug: "civicrelay",
    name: "CivicRelay",
    desc: "Report local civic issues with photo and location — routes them to the right municipal department.",
    tags: ["Next.js", "Azure Functions", "Cosmos DB"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/CivicRelay",
    slot: "c",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js" },
      { layer: "API", tech: "Azure Functions" },
      { layer: "Database", tech: "Azure Cosmos DB" },
    ],
    features: [
      { title: "Photo + location reports", body: "Citizens snap a photo and drop a pin; the report is geotagged automatically." },
      { title: "Department routing", body: "Reports are routed to the correct municipal department based on category and location." },
    ],
    getStarted: [
      "Open the app and allow location access.",
      "Snap a photo of the issue and pick a category.",
      "Submit — the report is routed automatically.",
    ],
  },
  {
    slug: "cloud-portfolio",
    name: "Cloud Portfolio",
    desc: "This site — static Next.js frontend on Azure Static Web Apps, backed by Azure Functions and Cosmos DB.",
    tags: ["Next.js", "Azure SWA", "Azure Functions", "Python"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/Cloud-Portfolio",
    slot: "d",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js (static export)" },
      { layer: "Hosting", tech: "Azure Static Web Apps" },
      { layer: "Backend", tech: "Azure Functions (Python)" },
      { layer: "Database", tech: "Azure Cosmos DB" },
    ],
    features: [
      { title: "Interactive starfield", body: "A canvas-rendered night sky with real IAU constellations, comets, and giant stars runs behind every page." },
      { title: "Serverless visitor counter", body: "An Azure Function backed by Cosmos DB tracks page views without a server to manage." },
    ],
    getStarted: [
      "You're looking at it — scroll through About, Projects, and Hobbies.",
      "The source is on GitHub if you want to see how it's built.",
    ],
  },
  {
    slug: "employee-leave-portal",
    name: "Employee Leave Portal",
    desc: "Leave management system with approval workflows and a full CI/CD pipeline.",
    tags: ["Python", "Flask", "MySQL", "Docker", "Jenkins"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/Employee_leave_portal",
    slot: "e",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Backend", tech: "Python + Flask" },
      { layer: "Database", tech: "MySQL" },
      { layer: "Containerization", tech: "Docker" },
      { layer: "CI/CD", tech: "Jenkins" },
    ],
    features: [
      { title: "Approval workflows", body: "Leave requests move through manager approval before being finalized." },
      { title: "Full CI/CD pipeline", body: "Jenkins builds, tests, and deploys the containerized app on every push." },
    ],
    getStarted: [
      "Clone the repo and run docker-compose up.",
      "Log in as an employee or manager to see the two workflows.",
    ],
  },
]
